language: python

python:
  - "2.7"

cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-dev
      - python-lxml  # because pip installation is slow
      - python-numpy
      - python-simplejson
      - python-serial
      - python-matplotlib  # For runbot badges


sudo: required  # Required for docker
services:
  - docker

env:
  global:
  - VERSION="9.0" TESTS="0" LINT_CHECK="0"
  - secure: "L3XkViRWCtm3pLXDqNAyDQmMLXNqTowU3imL1l/TSr81RnPmTE3O8YhkX+sJQeHASTLUAcymTZFVSido7pbzBYdMqpMYOQbNV17fJQmIHA3IcEi4WhjH7MDdczs78rm0a8v01kibZ3JzvMDpS15o6ESJdsTpPGctUC3G1rG1sh8="
  - secure: "Stym6U51YxobNVlbMrsgBzeebO0Gzoj0HQZ6p2Wo64ccS9txVSDvp37OkpB78yP7n7I3Dw7BaOIRp6h8wU8r5kjgAGPEaZJoZ9kRvdw+b6Do2qysSSE1p11agx9XHjfVSXEjJsqMD4PMpZPsI4mnP/Q4QFHGtsvD1QCTN33GXcU="
  - secure: "dUuHLT+R/eYRcrDOYa/4zbKVHCBoWS5vSVM5bH7e4WAddquhftPop6Iyxq0lfwWnXsYql1YyS9x152ZjYFpY4DzVbdDYoOWBFN9PRk5rF0ptxkoa7+ZgF0+anV+3owpY5xtC9fUmP/uPRNQDJUv+/2jNXWQDShd7WZx+Qo4XnJA="
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE=runbot_selftest,runbot_travis2docker,runbot_send_email
    # - TESTS="1" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/Vauxoo/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - pip install gitlab3
  - pip install docker-py
  - pip install --upgrade --pre travis2docker
  - travis_install_nightly
  - git clone --depth=1 https://github.com/odoo/odoo-extra ~/odoo-extra
  - sed -i '/from matplotlib.font_manager import FontProperties/d' ~/odoo-extra/runbot/runbot.py
  - sed -i '/from matplotlib.textpath import TextToPath/d' ~/odoo-extra/runbot/runbot.py
  - sed -i '/'matplotlib'/d' ~/odoo-extra/runbot/__openerp__.py
  - sed -i "/import test_crawl/d" ~/odoo-extra/runbot/__init__.py
  - sed -i 's/base.menu_config/base.menu_administration/g' ~/odoo-extra/runbot/res_config_view.xml
  # Change cron interval to avoid interference with tests
  - sed -i "s/'interval_number'>1</'interval_number'>60</g" ~/odoo-extra/runbot/runbot.xml

  # odoo-extra has a bunch of v9 modules which aren't compatible, remove them
  - (cd ~/odoo-extra; rm -rf $(ls | grep -v runbot$))
  - if [ "${TESTS}" == "1"  ]; then travis_wait docker pull vauxoo/odoo-80-image-shippable-auto; fi

script:
  - travis_wait travis_run_tests

after_success:
  - travis_after_tests_success
