language: python

python:
  - "2.7"

cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-dev
      - python-lxml  # because pip installation is slow
      - python-numpy
      - python-simplejson
      - python-serial
      - python-matplotlib  # For runbot badges


sudo: required  # Required for docker
services:
  - docker

env:
  global:
  - VERSION="9.0" TESTS="0" LINT_CHECK="0"
  # The module "runbot_send_email" show the error "Connection timed out" when use real credentials but in local run fine!
  # TODO: Enable email sending from travis
  # - secure: fZ4S2vmcIJyxdMk9nZqFPvbSzWZVQWIoulzqJGGQLYKIERVwpM2RI5u0v0ruLlvqsGWR1IJy+ZkAG/w7FiMbUuatYWOCV6+e13nuAIFlg+d3u9v4jt1mkkDQOJS/zVy7IM/mBf8x+USLJq1vSHlrMlr1kwgUQHlAlCn9f/ToVl4=
  # - secure: KWy09oZAEBjKbr2lUFS6UVxlwvLj/PBB17+rSIiajWwNLm0NbN4VnHjMsCBnOgYlcuKQWJASXEqmhozWCOFjDHvJ8+irEgCsdJ1pfusMbRMk6c9Z2zBdtvKyl84RX5g+I/au1JEVUp1Hs+kBzdgR6wvmLtFyid54jgD0IdN3gUA=
  # - secure: fZPEKMZyeMTusAW79+EWNm01Ynnv0OPM5UHLAEaf7qvh9JWi+XYwIQNDxPZEH5FmDZ/psRpkByag9zkwy9r88UyiA7P7vJP/cnYc04IS31CqABRGhr4ZRX7yyO39LpaZJR1PQP954tGe5BEQoOUM4YXrnnZJ863J1vsqesUFGHA=
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="vauxoo/odoo" INCLUDE=runbot_selftest,runbot_travis2docker,runbot_send_email
    # - TESTS="1" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/Vauxoo/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - if [[ "${TESTS}" == "1"   ]]; then ${TRAVIS_BUILD_DIR}/.travis_requirements.sh; fi

script:
  - docker run -d -p 5000:5000 --name registry registry:2
  - travis_run_tests

after_success:
  - travis_after_tests_success
